version: '3'

services:
  semantic-service:
    build: .
    container_name: semantic-service
    external_links:
      - camera-service
      - density-service
      - volume-service
#    ports:
#      - "50049:50049"
    restart: always
    networks:
      - default
      - camera_default
      - volume-of-vehicles-cpp_default
      - density-of-vehicles_default

networks:
  camera_default:
    external: true
  volume-of-vehicles-cpp_default:
    external: true
  density-of-vehicles_default:
    external: true

